server:
  port: 8082
spring:
  application:
    name: PHOTO-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      uri: http://localhost:8085
  profiles:
    active:
    - dev

