server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictu_photos
    username: pictu
    password: mynewpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: PHOTO-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

